#basic things
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-archives
  - jekyll-include-cache

#breadcrumbs
permalink: /:categories/:title/
breadcrumbs: true

#theme skin
minimal_mistakes_skin: "contrast"

#seo shit
title: &name "Andrew Kallio"
name: *name
description: "For those of you who are actually interested in my thoughts."
url: https://andrewkallio.me

#home page
paginate: 5
paginate_path: /:categories/:title/
author_profile: true

#footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adwk_"

    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kallioandrew"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "#"

#sidebar author
author:
  name: "Andrew Kallio II"
  avatar: profile.jpg
  bio: "17 year old student from the town of Cincinnati, Ohio. Since my amazing birth, I've moved to Omaha, Nebraska where I have furtherd my interest in technology and creative arts. I am interested in anything that has to do with technology."
  location: "Omaha, Nebraska"

#posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      breadcrumbs: true

# theme documentation https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
